name: ubuntu

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/windows.yml

jobs:
  test-linux:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1' ]
        experimental: [false]
        include:
          - ruby: '3.2'
            experimental: true
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Update gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run specs
        run: |
          bundle exec rake
